Repository Mohit5Upadhyay/WeatherApplication, pull requests merged in 2024-10, with the labels that each got.

#41 added dark mode feature
  index.html
  script.js
  style.css
Labels: hacktoberfest

#72 add Chatbot to the Website
  .env.example
  api_key
  chatbot.gif
  chatbot.html
  index.html
  weather.png
Labels: hacktoberfest, gssoc-extd

#80 Developed [Feature ] #58 :Provide information on air quality
  index.html
  script.js
  style.css
Labels: hacktoberfest, gssoc-extd

#91 # issue 84
  about.css
  about.html
  clime.png
  contact.css
  contact.html
  index.html
  logoo.png
  style.css
Labels: gssoc-extd
